/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_nf3_action_meta` VALUES
(386,18,"objectType","Action","objectType","Action"),
(387,18,"objectDomain","actions","objectDomain","actions"),
(388,18,"editActive","","editActive",""),
(389,18,"message","Your form has been successfully submitted.","message","Your form has been successfully submitted."),
(390,18,"order","1","order","1"),
(391,18,"payment_gateways","","payment_gateways",""),
(392,18,"payment_total","0","payment_total","0"),
(393,18,"tag","","tag",""),
(394,18,"to","{wp:admin_email}","to","{wp:admin_email}"),
(395,18,"reply_to","","reply_to",""),
(396,18,"email_subject","Ninja Forms Submission","email_subject","Ninja Forms Submission"),
(397,18,"email_message","{fields_table}","email_message","{fields_table}"),
(398,18,"email_message_plain","","email_message_plain",""),
(399,18,"from_name","","from_name",""),
(400,18,"from_address","","from_address",""),
(401,18,"email_format","html","email_format","html"),
(402,18,"cc","","cc",""),
(403,18,"bcc","","bcc",""),
(404,18,"redirect_url","","redirect_url",""),
(405,18,"submitter_email","","submitter_email",""),
(406,18,"fields-save-toggle","save_all","fields-save-toggle","save_all"),
(407,18,"exception_fields","a:0:{}","exception_fields","a:0:{}"),
(408,18,"set_subs_to_expire","0","set_subs_to_expire","0"),
(409,18,"subs_expire_time","90","subs_expire_time","90"),
(410,18,"success_msg","Your form has been successfully submitted.","success_msg","Your form has been successfully submitted."),
(411,19,"objectType","Action","objectType","Action"),
(412,19,"objectDomain","actions","objectDomain","actions"),
(413,19,"editActive","","editActive",""),
(414,19,"order","2","order","2"),
(415,19,"message","This action adds users to WordPress\' personal data delete tool, allowing admins to comply with the GDPR and other privacy regulations from the site\'s front end.","message","This action adds users to WordPress\' personal data delete tool, allowing admins to comply with the GDPR and other privacy regulations from the site\'s front end."),
(416,19,"payment_gateways","","payment_gateways",""),
(417,19,"payment_total","0","payment_total","0"),
(418,19,"tag","","tag",""),
(419,19,"to","{wp:admin_email}","to","{wp:admin_email}"),
(420,19,"reply_to","","reply_to",""),
(421,19,"email_subject","Ninja Forms Submission","email_subject","Ninja Forms Submission"),
(422,19,"email_message","{fields_table}","email_message","{fields_table}"),
(423,19,"email_message_plain","","email_message_plain",""),
(424,19,"from_name","","from_name",""),
(425,19,"from_address","","from_address",""),
(426,19,"email_format","html","email_format","html"),
(427,19,"cc","","cc",""),
(428,19,"bcc","","bcc",""),
(429,20,"objectType","Action","objectType","Action"),
(430,20,"objectDomain","actions","objectDomain","actions"),
(431,20,"editActive","","editActive",""),
(432,20,"order","3","order","3"),
(433,20,"message","This action adds users to WordPress\' personal data export tool, allowing admins to comply with the GDPR and other privacy regulations from the site\'s front end.","message","This action adds users to WordPress\' personal data export tool, allowing admins to comply with the GDPR and other privacy regulations from the site\'s front end."),
(434,20,"payment_gateways","","payment_gateways",""),
(435,20,"payment_total","0","payment_total","0"),
(436,20,"tag","","tag",""),
(437,20,"to","{wp:admin_email}","to","{wp:admin_email}"),
(438,20,"reply_to","","reply_to",""),
(439,20,"email_subject","Ninja Forms Submission","email_subject","Ninja Forms Submission"),
(440,20,"email_message","{fields_table}","email_message","{fields_table}"),
(441,20,"email_message_plain","","email_message_plain",""),
(442,20,"from_name","","from_name",""),
(443,20,"from_address","","from_address",""),
(444,20,"email_format","html","email_format","html"),
(445,20,"cc","","cc",""),
(446,20,"bcc","","bcc",""),
(447,20,"redirect_url","","redirect_url",""),
(448,20,"submitter_email","email_1560359777188","submitter_email","email_1560359777188"),
(449,20,"fields-save-toggle","save_all","fields-save-toggle","save_all"),
(450,20,"exception_fields","a:0:{}","exception_fields","a:0:{}"),
(451,20,"set_subs_to_expire","0","set_subs_to_expire","0"),
(452,20,"subs_expire_time","90","subs_expire_time","90");
